const fs = require('fs');
const path = require('path');
const yaml = require('js-yaml');
const ssri = require('ssri');

const vendorsFile = fs.readFileSync(
  path.join(path.dirname(require.resolve('hexo-theme-next')), '_vendors.yml')
);
const dependencies = yaml.load(vendorsFile);
const newPlugins = require('../package.json').dependencies;

// Generate Subresource Integrity(SRI) via ssri
async function generateSRI(name, file) {
  let content = '';
  const asset = './node_modules/' + name + '/' + file;
  await ssri
    .fromStream(fs.createReadStream(asset), { algorithms: ['sha256'] })
    .then(sri => { content += sri });
  return content;
}

async function main() {
  for (const [key, value] of Object.entries(dependencies)) {
    const { name, file } = value;
    const dep = dependencies[key];
    dep['version'] = newPlugins[name];
    if(process.argv[2] === '--without-integrity')
      continue;
    dep['integrity'] = await generateSRI(name, file);
  }
  const dump =
    '# This file is automatically generated\n' +
    '# See https://github.com/next-theme/plugins\n\n' +
    yaml.dump(dependencies);
  try {
    fs.writeFileSync('_vendors.yml', dump);
  } catch (error) {
    console.log(error)
  }
}

main();
